In [35]:
import pandas as pd
csvfile="pdssample.csv"
df=pd.read_csv(csvfile,encoding='utf-8')

df

Roll     Name  Sem1  sem2  sem3
0     1   Ratish  9.20  9.00  8.90
1     2    Soham  9.06  9.10  9.00
2     3      Ram  9.00  8.80  8.90
3     4    Shyam  9.00  9.00  9.00
4     5    Maddy  9.00  7.80  8.00
5     6   Shreya  8.80  8.90  9.00
6     7  Anirudh  7.80  8.00  8.50
7     8   Vijay   9.50  9.20  8.90
8     9       M3  8.80  8.78  8.89
9    10      Boy  9.50  9.50  9.50

In [36]:
print(df.head)
print("__________________________________________________________________")
print(df.tail)

<bound method NDFrame.head of    Roll     Name  Sem1  sem2  sem3
0     1   Ratish  9.20  9.00  8.90
1     2    Soham  9.06  9.10  9.00
2     3      Ram  9.00  8.80  8.90
3     4    Shyam  9.00  9.00  9.00
4     5    Maddy  9.00  7.80  8.00
5     6   Shreya  8.80  8.90  9.00
6     7  Anirudh  7.80  8.00  8.50
7     8   Vijay   9.50  9.20  8.90
8     9       M3  8.80  8.78  8.89
9    10      Boy  9.50  9.50  9.50>
__________________________________________________________________
<bound method NDFrame.tail of    Roll     Name  Sem1  sem2  sem3
0     1   Ratish  9.20  9.00  8.90
1     2    Soham  9.06  9.10  9.00
2     3      Ram  9.00  8.80  8.90
3     4    Shyam  9.00  9.00  9.00
4     5    Maddy  9.00  7.80  8.00
5     6   Shreya  8.80  8.90  9.00
6     7  Anirudh  7.80  8.00  8.50
7     8   Vijay   9.50  9.20  8.90
8     9       M3  8.80  8.78  8.89
9    10      Boy  9.50  9.50  9.50>


In [37]:
cars={"BMW":['M3','X6',"M5","i8"],"Lamborghini":["Aventador","Revuelto","Urus","Countach"],"Koeniggsegg":["Gemera","Regera","Agera R","CCX"]}
df1=pd.DataFrame(cars)
df1

BMW Lamborghini Koeniggsegg
0  M3   Aventador      Gemera
1  X6    Revuelto      Regera
2  M5        Urus     Agera R
3  i8    Countach         CCX

In [38]:
print(df[['Name']])
print()
print(df[['Name','Sem1']])

      Name
0   Ratish
1    Soham
2      Ram
3    Shyam
4    Maddy
5   Shreya
6  Anirudh
7   Vijay 
8       M3
9      Boy

      Name  Sem1
0   Ratish  9.20
1    Soham  9.06
2      Ram  9.00
3    Shyam  9.00
4    Maddy  9.00
5   Shreya  8.80
6  Anirudh  7.80
7   Vijay   9.50
8       M3  8.80
9      Boy  9.50


In [39]:
df.set_index("Roll")
df.loc[1,'Sem1']

9.06

In [40]:
df.iloc[0:2,0:3]

Roll    Name  Sem1
0     1  Ratish  9.20
1     2   Soham  9.06

In [41]:
df["Sem1"]>=9

0     True
1     True
2     True
3     True
4     True
5    False
6    False
7     True
8    False
9     True
Name: Sem1, dtype: bool

In [42]:
df.to_csv("New.csv")

In [45]:
import numpy as np
a=[[11,12,13],[21,22,23],[31,32,33]]
arr=np.array(a)
arr

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [47]:
print(arr.shape)
arr.size

(3, 3)


9

In [48]:
arr*2

array([[22, 24, 26],
       [42, 44, 46],
       [62, 64, 66]])

In [50]:
x=np.array([[1,0],[0,1]])
y=np.array([[2,3],[3,2]])
print(x*y)
print(np.dot(x,y))

[[2 0]
 [0 2]]
[[2 3]
 [3 2]]
